name: macOS Release Build

on:
  push:
    tags:
      - 'v*' 
jobs:
  release: 
    runs-on: macos-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.10' 

      - name: Build executable
        id: build 
       run: | 
          swift build -c release --product combr
          
          chmod +x .build/release/combr
          
          echo "asset_path=.build/release/combr" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }} 
          name: Release ${{ github.ref_name }} 
          generate_release_notes: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
